logging:
  level:
    root: INFO
#    org.hibernate: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework.jdbc: DEBUG

security:
   basic:
       enabled: false
management:
   security:
       enabled: false

---
spring:
   profiles: dev
   datasource:
       driver-class-name: org.postgresql.Driver
       url: jdbc:postgresql://localhost:5432/postgres
       username: postgres
       password: postgres
server:
   port: 18181
---
spring:
    profiles: heroku
    datasource:
        url: ${DATABASE_URL}
        driverClassName: org.postgresql.Driver
        maxActive: 10
        maxIdle: 5
        minIdle: 2
        initialSize: 5
        removeAbandoned: true