logging:
  level:
    root: INFO
#    org.hibernate: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework.jdbc: DEBUG

security:
   basic:
       enabled: false
management:
   security:
       enabled: false

---
spring:
   profiles: dev
   datasource:
       driver-class-name: org.postgresql.Driver
       url: jdbc:postgresql://localhost:5432/postgres
       username: ${abc}
       password: postgres
       maxActive: 10
       maxIdle: 5
       minIdle: 2
       initialSize: 5
       removeAbandoned: true
server:
   port: 18181
---
spring:
    profiles: heroku
    datasource:
        driverClassName: org.postgresql.Driver
        url: ${JDBC_DATABASE_URL}
        maxActive: 10
        maxIdle: 5
        minIdle: 2
        initialSize: 5